name=Result
version=0.2.0
author=Tobias Knauss <tobias.knauss@web.de>
maintainer=Tobias Knauss <tobias.knauss@web.de>
sentence=Common results and common failures collection
paragraph=A collection of frequently used function results (return values): common results, common failures.
category=Other
url=https://github.com/TobiasKnauss/ArduinoLib_Result
architectures=*
